/**
 * Skutečná jména ostrovů, jen písmena, bez přípony Island a podobně.
 * Trénink Markovova řetězce. Žádné jméno se nesmí vygenerovat znovu.
 */
export const ISLAND_CORPUS = [
  "skye", "mull", "iona", "jura", "islay", "arran", "bute", "rum", "eigg", "coll",
  "tiree", "colonsay", "gigha", "barra", "lewis", "harris", "foula", "stronsay", "sanday", "shapinsay",
  "rousay", "hoy", "flotta", "unst", "yell", "fetlar", "whalsay", "bressay", "mousa", "noss",
  "staffa", "lismore", "seil", "luing", "shuna", "kerrera", "ulva", "erraid", "scarba", "oronsay",
  "vatersay", "mingulay", "pabbay", "eriskay", "sandray", "vatersa", "hellisay", "gigalum", "berneray", "scalpay",
  "raasay", "rona", "canna", "muck", "soay", "taransay", "scarbaigh", "wiay", "grisay", "en say",
  "malta", "gozo", "comino", "sicily", "sardinia", "corsica", "elba", "capri", "ischia", "procida",
  "stromboli", "vulcano", "lipari", "salina", "panarea", "filicudi", "alicudi", "pantelleria", "lampedusa", "linosa",
  "favignana", "levanzo", "marettimo", "ustica", "ponza", "ventotene", "capraia", "giglio", "giannutri", "pianosa",
  "caprera", "maddalena", "budelli", "spargi", "molara", "tavolara", "asinara", "santantioco", "sanpietro", "marettima",
  "crete", "rhodes", "kos", "patmos", "samos", "chios", "lesbos", "lemnos", "thasos", "skiathos",
  "skopelos", "skyros", "andros", "tinos", "mykonos", "naxos", "paros", "ios", "santorini", "folegandros",
  "sikinos", "milos", "sifnos", "serifos", "kythnos", "kea", "syros", "amorgos", "anafi", "donousa",
  "koufonisia", "iraklia", "schinoussa", "antiparos", "delos", "rhea", "hydra", "spetses", "poros", "aegina",
  "salamina", "kythira", "antikythira", "kastellorizo", "symi", "tilos", "nisyros", "kalymnos", "leros", "lipsi",
  "ikaria", "fourni", "psara", "oinousses", "samothrace", "alonnisos", "skiros", "paxoi", "antipaxos", "corfu",
  "cyprus", "aruba", "curacao", "bonaire", "trinidad", "tobago", "margarita", "cozumel", "roatan", "utila",
  "guanaja", "barbados", "grenada", "dominica", "antigua", "barbuda", "montserrat", "nevis", "saba", "anguilla",
  "martinique", "guadeloupe", "mariegalante", "desirade", "tortola", "virgin", "anegada", "jost", "beef", "norman",
  "peter", "salt", "cooper", "ginger", "greatcamanoe", "inagua", "eleuthera", "abaco", "exuma", "bimini",
  "mayaguana", "acklins", "rumcay", "samana", "saona", "catalina", "beata", "gonave", "tortuga", "jamaica",
  "cuba", "hispaniola", "puertorico", "vieques", "culebra", "mona", "monito", "desecheo", "stcroix", "stjohn",
  "stthomas", "grandcayman", "caymanbrac", "providencia", "sanandres", "coiba", "contadora", "taboga", "delrey", "boa",
  "madeira", "porto", "azores", "sao", "miguel", "terceira", "faial", "pico", "saojorge", "graciosa",
  "flores", "corvo", "canary", "tenerife", "gran", "lanzarote", "fuerteventura", "lagomera", "lahierro", "lapalma",
  "iceland", "greenland", "faroe", "bornholm", "gotland", "oland", "aland", "hiumaa", "saaremaa", "muhu",
  "rugen", "usedom", "fehmarn", "sylt", "fohr", "amrum", "pellworm", "helgoland", "hiddensee", "poel",
  "bornholma", "gotska", "faro", "vens", "hallands", "orust", "tjorn", "karmoy", "stord", "bømlo",
  "senja", "kvaloya", "ringvassoy", "soroya", "seiland", "stjernoya", "rolvsoy", "ingoya", "masoy", "havoya",
  "hokkaido", "honshu", "shikoku", "kyushu", "okinawa", "ishigaki", "miyako", "iriomote", "yonaguni", "amami",
  "yakushima", "tanegashima", "sado", "okushiri", "rebun", "rishiri", "teuri", "yagishiri", "okushirito", "awaji",
  "shodo", "naoshima", "teshima", "inujima", "megijima", "ogijima", "shodoshima", "miyajima", "itsukushima", "oshima",
  "nijima", "kozushima", "miyake", "hachijo", "aogashima", "torishima", "iojima", "chichijima", "hahajima", "anijima",
  "tahiti", "moorea", "bora", "huahine", "raiatea", "tahaa", "maupiti", "rangiroa", "fakarava", "tikehau",
  "manihiki", "penrhyn", "rarotonga", "aitutaki", "mangaia", "mauke", "mitiaro", "niue", "tongatapu", "vavau",
  "haapai", "eua", "niuatoputapu", "savaii", "upolu", "tutuil a", "of u", "tau", "ofu", "olosega",
  "fiji", "viti", "vanua", "kadavu", "ovalau", "taveuni", "gau", "koro", "moturiki", "beqa",
  "guam", "saipan", "tinian", "rota", "palau", "babeldaob", "koror", "pelel iu", "angaur", "yap",
  "chuuk", "pohnpei", "kosrae", "truk", "nauru", "tarawa", "kiritimati", "malden", "starbuck", "caroline",
  "hawaii", "maui", "oahu", "kauai", "molokai", "lanai", "niihau", "kahoolawe", "santa", "catalina",
  "cruz", "rosa", "miguel", "anacapa", "san", "clemente", "nicolas", "barbara", "channel", "farallon",
  "madagascar", "reunion", "mauritius", "rodrigues", "seychelles", "mahe", "praslin", "ladigue", "zanzibar", "pemba",
  "mafia", "comoros", "mayotte", "anjouan", "moheli", "grande", "socotra", "bahrain", "qeshm", "kish",
  "hormuz", "lavan", "kharg", "failaka", "bubiyan", "warbah", "sirri", "abu", "musa", "tunb",
  "sri", "lanka", "maldives", "male", "baa", "ari", "addu", "fuvahmulah", "hulhumale", "thoddoo",
  "andaman", "nicobar", "havelock", "neil", "baratang", "long", "rutland", "little", "camorta", "katchal",
  "nancowry", "car", "teressa", "chowra", "battimalv", "phuket", "samui", "phangan", "tao", "chang",
  "lanta", "yao", "phi", "samet", "sichang", "lankawi", "penang", "pangkor", "redang", "perhentian",
  "tioman", "sipadan", "mabul", "kapalai", "bal i", "lombok", "sumbawa", "sumba", "flores", "timor",
  "alor", "wetar", "buru", "seram", "halmahera", "morotai", "ternate", "tidore", "biak", "yapen",
  "misool", "waigeo", "batanta", "salawati", "komodo", "rin ca", "padar", "gili", "nusa", "lembongan",
  "penida", "ceningan", "serangan", "menjangan", "tabuhan", "benggala", "raja", "ampat", "wayag", "fam",
  "tasmania", "kangaroo", "fraser", "moreton", "stradbroke", "magnetic", "dunk", "hinchinbrook", "whitsunday", "hamilton",
  "hook", "hayman", "daydream", "longisland", "keswick", "brampton", "lindeman", "shaw", "hookisland", "dent",
  "nz", "north", "south", "stewart", "waiheke", "rangitoto", "motutapu", "browns", "kawau", "greatbarrier",
  "rakino", "motuihe", "rotoroa", "pakatoa", "ponui", "pakihi", "kaikoura", "arapawa", "durville", "d urville",
  "chatham", "pitt", "rekohu", "mangere", "rautini", "houruakopara", "sisters", "forty", "fours", "pyramid",
  "auckland", "enderby", "adams", "disappointment", "ewing", "rose", "ocean", "friday", "dundas", "green",
  "campbell", "dentisland", "jacquemart", "folly", "macquarie", "heard", "mcdonald", "kerguelen", "crozet", "amsterdam",
  "paula", "possession", "est", "cochon", "pingouins", "apotres", "marion", "prince", "edward", "bouvet",
  "icelandic", "heimaey", "grimsey", "flatey", "hrisey", "vidoy", "streymoy", "estro y", "sandoy", "vagar",
  "mykines", "kalsoy", "kunoy", "bordoy", "svinoy", "fugloy", "norderney", "juist", "langeoog", "spiekeroog",
  "wangerooge", "baltrum", "borkum", "memmert", "lutjehorn", "scharhorn", "neuwerk", "scharhoern", "grosser", "knechtsand",
] as const;
